model:
  model_config: "sam2_hiera_t.yaml"
  pretrain_model_path: "/home/zly/multi_ob/segment-anything-2/checkpoints/sam2_hiera_tiny.pt"
train:
  device: "cuda"
  learning_rate: 2e-5
  num_epochs: 5
  save_path: 'data2/zly/training/'
  batch_size_one_gpu: 2
log:
  tensorboard_log_dir: './logs_tensorboard'
  loguru_log_file: './logs/train/training.log'
  log_interval: 10 
  exp_name: "sam2_t"
dataset:
  train_dataloader: MOTS
  train_dataset_root_path: "/data2/zly/mots_data/MOTS2020/train"
  val_dataloader: MOTS
  val_dataset_root_path: "/data2/zly/mots_data/MOTS2020/train"
  test_dataloader: MOTS
  test_dataset_root_path: "/data2/zly/mots_data/MOTS2020/test"
