model:
  model_config: "sam2_hiera_l.yaml"
  # pretrain_model_path: "/data3/zly/multi_ob/segment-anything-2/checkpoints/sam2.1_hiera_large.pt"
  # pretrain_model_path: "/data2/zly/training/2024-11-02-22-57/model_epoch_12.pth"
  # pretrain_model_path: "/data2/zly/training/2024-11-07-20-29/model_epoch_3.pth"
  # pretrain_model_path: "/data2/zly/training/2024-11-12-11-21/model_epoch_5.pth"  # 2024-11-12修改了loss函数和res_iou_head的
  # pretrain_model_path: "/data2/zly/training/2024-11-17-00-15/model_epoch_2.pth" # 2024-11-18添加了crodhuman的模型
  trainable_layers:
    - "sam_mask_decoder.person_classifier_mlp.layers"
    - "sam_mask_decoder.person_classifier_token"
    - "sam_mask_decoder.hq_token"
    - "sam_mask_decoder.hf_mlp.layers"
    - "sam_mask_decoder.compress_feature_2"
    - "sam_mask_decoder.compress_feature_1"
    - "sam_mask_decoder.compress_feature_0"
    - "sam_mask_decoder.res_iou_mlp"
train:
  learning_rate: 3e-5
  weight_decay: 0.1
  warm_up_step_ratio: 0.05
  max_norm: 0.1
  num_epochs: 5
  save_path: '/data2/zly/training/'
  batch_size_one_gpu: 32
  validate_first: False
  num_workers_dataloader: 16
  transfer_image_in_dataset_use_sam2: True
  valid_every_train_epoch: 1
  continue_training: False
  lr_multiple_for_new_param: 10
log:
  tensorboard_log_dir: './logs_tensorboard'
  loguru_log_file: './logs/train/training_cuda_data_mix_after_11-11.log'
  log_interval_batch: 12
  exp_name: "sam2_large"

  # train_dataloader: MOTS
  # train_dataset_root_path: "/data2/zly/mots_data/MOTS2020/train"
  # val_dataloader: MOTS
  # val_dataset_root_path: "/data2/zly/mots_data/MOTS2020/train"
  # test_dataloader: MOTS
  # test_dataset_root_path: "/data2/zly/mots_data/MOTS2020/test"
  # train_dataloader: openimagev7
  # train_dataset_root_path: "/data2/zly/OIv7/OIv7coco/data"
  # train_annotation_file: "/data2/zly/OIv7/OIv7coco/labels.json"
  # val_dataloader: openimagev7
  # val_dataset_root_path: "/data2/zly/OIv7/OIv7coco/data"
  # val_annotation_file: "/data2/zly/OIv7/OIv7coco/labels.json"
  # train_dataloader: samacoco
  # train_dataset_root_path:   "/data3/zly/samacoco/samacocoperson/data"
  # train_annotation_file:     "/data3/zly/samacoco/samacocoperson/labels.json"
  # val_dataloader: samacoco
  # val_dataset_root_path:     "/data3/zly/samacoco/samacocoperson_valid/data"
  # val_annotation_file:       "/data3/zly/samacoco/samacocoperson_valid/labels.json"
  # val_length: -1
dataset:
  use_mix_mode: true  # 开启混合模式
  train_datasets:
    - name: MOTS
      path: "/data2/zly/mots_data/MOTS2020/train"
      ratio: 0.05
    - name: samacoco
      path: "/data3/zly/samacoco/samacocoperson/data"
      annotation_file: "/data3/zly/samacoco/samacocoperson/labels.json"
      ratio: 1
    - name: crowdhuman
      path: "/data2/zly/mot_data/crowdhuman/Images"
      annotation_file: "/data2/zly/mot_data/crowdhuman/selected_filter_auto_mask_cw_train_split.json"
      ratio: 1
  val_datasets:
    - name: MOTS
      path: "/data2/zly/mots_data/MOTS2020/train"
      ratio: 0.05
      val_lenth: 1024
    - name: samacoco
      path: "/data3/zly/samacoco/samacocoperson_valid/data"
      annotation_file: "/data3/zly/samacoco/samacocoperson_valid/labels.json"
      ratio: 1
      val_length: 4096
    - name: crowdhuman
      path: "/data2/zly/mot_data/crowdhuman/Images"
      annotation_file: "/data2/zly/mot_data/crowdhuman/SAM2_visualizations_val_crop_image/annotations.json"
      ratio: 1
      val_length: 4096
test:
  use_hq: True
  use_res_iou: True
  pred_iou_thresh: 0.3
  stability_score_thresh: 0.6
  person_probability_thresh: 0.8

